version: '3.8'

services:
  # 1. Database Server (MySQL)
  # Hanya bisa diakses langsung via localhost (Simulasi Server Lokal)
  db:
    image: mysql:5.7
    container_name: raya_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: raya_corp_db
      MYSQL_USER: raya_user
      MYSQL_PASSWORD: raya_password
    ports:
      - "127.0.0.1:3306:3306" # Binding ke localhost agar tidak terekspos ke internet publik
    networks:
      - raya_network
    volumes:
      - db_data:/var/lib/mysql

  # 2. Web Server (Apache + PHP)
  web:
    build: .
    container_name: raya_web
    depends_on:
      - db
    ports:
      - "8080:80" # Web bisa diakses publik di port 8080
    networks:
      - raya_network
    volumes:
      - ./src:/var/www/html

networks:
  raya_network:
    driver: bridge

volumes:

  db_data:
